# Generated by Django 4.2 on 2023-04-21 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date of session')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='windcockpit.spot')),
            ],
        ),
    ]
