# Generated by Django 4.2 on 2023-04-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windcockpit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='max_speed',
            field=models.FloatField(default=0),
        ),
    ]
